# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Do not pay attention to this parameter
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vm.provider :virtualbox do |vb|
      config.vbguest.auto_update = false
    end
  end

  # Define the gitlab_server VM
  config.vm.define "docker_server" do |server|
    # Specify the Vagrant box to use
    server.vm.box = "centos/7"
    # Specify the VM ip address
    server.vm.network :private_network, ip: "30.30.30.3"
    # Specify the VM specs when using the Virtualbox provisioner
    server.vm.provider "virtualbox" do |vb|
      vb.name =  "docker.server.local"
      # VM RAM in MB
      vb.memory = 4096
      # VM CPUs
      vb.cpus = 2
    end
  end

  # Use Vagrant Ansible provisioner
  config.vm.provision "ansible_local" do |ansible|
    # The path to the playbooks entry point
    ansible.playbook = "playbooks/run.yml"
    # Only run the roles with these tags
    ansible.tags = "install"
  end

end
